//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeminarsAndLektors
    {
        public int Id { get; set; }
        public string LektorsName { get; set; }
        public int SeminarsId { get; set; }
    
        public virtual Lektors Lektors { get; set; }
        public virtual Seminars Seminars { get; set; }
    }
}
